name: Primeiro Workflow
on:
  push:
jobs:
  primerio-job:
    runs-on: ubuntu-latest
    setps:
      - run: echo "Primeiro passo"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
      - name: Status
        run: echo "Status ${{ job.status }}"